name: Verify

on:
  push:
    branches:
      - master

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven Dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: mvn-repository
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Create Docker Config
      run: mkdir -p ~/.docker && echo "{}" > ~/.docker/config.json
    - name: Build with Maven
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
        GPG_KEYNAME: ${{ secrets.GPG_PRIVATE_KEY_NAME }}
      run: |
        mkdir -p ~/.docker && echo "{}" > ~/.docker/config.json
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --no-tty --import
        sed -i 's@<password>__BINTRAY_TOKEN__.*$@<password>${{ secrets.BINTRAY_TOKEN }}</password>@g' ${{ github.workspace }}/.mvn/settings.xml
        mvn deploy --settings ${{ github.workspace }}/.mvn/settings.xml --batch-mode --no-transfer-progress -Pgpg,bintray -Dmaven.wagon.http.pool=false
